on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    name: Publish Docker containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activemq-version: ['5.16.3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Authenticate with registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ matrix.activemq-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.activemq-version }}
          labels: |
            version=${{ matrix.activemq-version }}

      - name: Publish containers
        uses: docker/build-push-action@v2
        with:
          context: .
          # TODO re-enable arm64
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            - ACTIVEMQ_VERSION=${{matrix.activemq-version}}